# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 18:45
from __future__ import unicode_literals

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_use_postgresql_json_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubuser',
            name='username',
            field=models.CharField(error_messages={b'unique': 'A user with that username already exists.'}, max_length=255, unique=True, validators=[django.contrib.auth.validators.ASCIIUsernameValidator()], verbose_name='username'),
        ),
    ]
