# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-27 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_username_hack'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='github_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
