# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-14 16:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_label_github_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitHead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fetched_at', models.DateTimeField(blank=True, null=True)),
                ('github_status', models.PositiveSmallIntegerField(choices=[(1, 'Awaiting creation'), (2, 'Awaiting update'), (3, 'Awaiting deletion'), (9, 'Saving'), (10, 'Fetched'), (21, 'Error while creating'), (22, 'Error while updating'), (23, 'Error while deleting'), (30, 'Error while fetching')], db_index=True, default=1)),
                ('ref', models.TextField(db_index=True)),
                ('sha', models.CharField(max_length=40)),
                ('etag', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='repository',
            name='git_heads_etag',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='repository',
            name='git_heads_fetched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='githead',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='git_heads', to='core.Repository'),
        ),
    ]
