# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-16 12:38
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_add_git_heads'),
    ]

    operations = [
        migrations.AddField(
            model_name='commit',
            name='parents',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=40), blank=True, null=True, size=None),
        ),
    ]
