# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-16 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_add_commit_parents'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='commits_parents_fetched',
            field=models.BooleanField(default=False),
        ),
    ]
