# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-19 21:37
from __future__ import unicode_literals

from django.db import migrations
import gim.core.utils


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_add_issue_commits_parents_fetched'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='pr_grouped_commits',
            field=gim.core.utils.JSONField(blank=True, null=True),
        ),
    ]
