# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 02:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_add_issue_pr_grouped_commits'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='has_projects',
            field=models.BooleanField(default=True),
        ),
    ]
