# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 18:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_add_repository_has_projects'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalHunkSplit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.TextField(blank=True, null=True)),
                ('line', models.TextField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_hunks_splits', to=settings.AUTH_USER_MODEL)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_hunks_splits', to='core.Repository')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='localhunksplit',
            unique_together=set([('repository', 'author', 'path', 'line')]),
        ),
    ]
