# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-29 13:06
from __future__ import unicode_literals

from django.db import migrations
import gim.core.utils


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpart',
            name='new_value',
            field=gim.core.utils.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventpart',
            name='old_value',
            field=gim.core.utils.JSONField(blank=True, null=True),
        ),
    ]
